#!/bin/bash

if [ -f /etc/os-release ]; then
    source /etc/os-release
    OS=$NAME
elif [ -f /etc/lsb-release ]; then
    source /etc/lsb-release
    OS=$DISTRIB_ID
else
    exit 1
fi

if [ "$OS" == "Ubuntu" ] || [ "$OS" == "Debian" ]; then
    apt-get update
    apt-get install -y nano ufw
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw allow 2096/tcp
    ufw --force enable
elif [ "$OS" == "CentOS Linux" ]; then
    yum install -y nano ufw
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw allow 2096/tcp
    ufw enable
    systemctl stop firewalld
    systemctl disable firewalld
else
    exit 1
fi

sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
sysctl -w net.ipv6.conf.lo.disable_ipv6=1

cd /etc/Aiko-Server || exit
rm -f rulelist

cat >rulelist <<EOF
.*whatismyip.*
(.*.||)(ipaddress|whatismyipaddress|whoer|iplocation|whatismyip|checkip|ipaddress|showmyip).(org|com|net|my|to|co|vn|my|io)
(.*\.||)(speed|speedtest|fast|speed.cloudflare|speedtest.xfinity|speedtestcustom|speedof|testmy|i-speed|speedtest.vnpt|nperf|speedtest.telstra|i-speed|merter|speed|speedcheck|zingfast)\.(com|$
EOF

aiko-server restart
clear
echo -e "\e[1;31mSpeedtest đã bị chặn!\e[0m"
